[package]
name = "sebaka"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8" }
heron = { version = "4", features = ["2d"] }
bevy_pancam = { version = "0.6.1" }
bevy_prototype_debug_lines = { version = "0.8.1" }
